spring:
  application:
    name: energycoop
  threads:
    virtual:
      enabled: true
  task:
    scheduling:
      pool:
        size: 5
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
    database-platform: org.hibernate.dialect.PostgreSQLDialect

scheduling:
  graig-fatha:
    schedule:
      energy-yield: "0 */15 * * * *"
      performance: "0 0 */6 * * *"

okta:
  oauth2:
    issuer: ${AUTH0_ISSUER}
    audience: ${AUTH0_AUDIENCE}
    client-id: ${AUTH0_CLIENT_ID}
    client-secret: ${AUTH0_SECRET}
    groupsClaim: permissions

external:
  api:
    graig-fatha:
      url: ${API_GRAIG_FATHA_URL}
      tid: ${API_GRAIG_FATHA_TID}
      key: ${API_GRAIG_FATHA_KEY}

site:
  rates:
    gf: ${SITE_RATES_GF}
  capacity:
    gf: ${SITE_CAPACITY_GF}

allowedOrigins: http://localhost:4200,https://energycoop-ui-production.up.railway.app,https://energy-coop-ui-staging.159.65.85.83.sslip.io
