spring:
    application:
        name: energycoop
    h2:
        console:
            enabled: true
    threads:
        virtual:
            enabled: true
    task:
        scheduling:
            pool:
                size: 5
    datasource:
        url: jdbc:h2:~/test
        username: sa
        password:
        driverClassName: org.h2.Driver
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        hibernate:
            ddl-auto: update

scheduling:
    enabled: true
    graig-fatha:
        schedule: "0 */15 * * * *"

external:
    api:
        graig-fatha:
            url: https://api.vensys.de:8443/api/v1.0
            tid: your_tid_here
            key: your_api_key_here